import Head from 'next/head'
import { Inter } from '@next/font/google'
import Table from '@/components/table'
import Form from '@/components/Form'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [visible, setVisible] = useState(false)

  const handler = () => {
    setVisible(!visible)
  }

  return (
    <section>
      <Head>
        <title>CRUD App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Booking Room
        </h1>

        <div className='container mx-auto flex justify-between py-5 border-b'>
          <div className='left flex gap-3'>
            <button onClick={handler} className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800'>
              Book Now
            </button>
          </div>
        </div>

        {/* collapseble form */}
        {visible ? <Form /> : <></>}

        {/* table */}
        <div className='container mx-auto'>
          <Table></Table>
        </div>
      </main>
    </section>
  )
}
